"""001 initial schema

Revision ID: 036a1db07894
Revises:
Create Date: 2026-03-21 17:31:55.135127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '036a1db07894'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('course_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('program', sa.String(length=100), nullable=True),
    sa.Column('season', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('suitable_for', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cta_url', sa.String(length=500), nullable=True),
    sa.Column('cta_label', sa.String(length=100), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('price_vnd', sa.BigInteger(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('course_id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('courses_suitable_for_gin', 'courses', ['suitable_for'], unique=False, postgresql_using='gin')
    op.create_index('courses_target_skills_gin', 'courses', ['target_skills'], unique=False, postgresql_using='gin')
    op.create_index('idx_courses_program_season', 'courses', ['program', 'season'], unique=False)
    op.create_table('mentors',
    sa.Column('mentor_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('specialty', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('programs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('max_students', sa.Integer(), nullable=False),
    sa.Column('active_students', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('mentor_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_mentors_email', 'mentors', ['email'], unique=False)
    op.create_index('mentors_programs_gin', 'mentors', ['programs'], unique=False, postgresql_using='gin')
    op.create_table('parents',
    sa.Column('parent_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('telegram_id', sa.String(length=100), nullable=True),
    sa.Column('student_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('parent_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('student_id')
    )
    op.create_index('idx_parents_email', 'parents', ['email'], unique=False)
    op.create_index('idx_parents_student_id', 'parents', ['student_id'], unique=False)
    op.create_table('students',
    sa.Column('student_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('ielts_score', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('sat_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('gpa', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('skill_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('target_schools', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('program', sa.String(length=100), nullable=True),
    sa.Column('months_enrolled', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('mentor_id', sa.Integer(), nullable=True),
    sa.Column('progress_pct', sa.Integer(), nullable=False),
    sa.Column('milestones_done', sa.Integer(), nullable=False),
    sa.Column('next_deadline', sa.Date(), nullable=True),
    sa.Column('next_deadline_label', sa.String(length=255), nullable=True),
    sa.Column('days_left', sa.Integer(), nullable=True),
    sa.Column('priority_action', sa.String(length=255), nullable=True),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('last_activity_date', sa.Date(), nullable=True),
    sa.Column('weakest_skill', sa.String(length=50), nullable=True),
    sa.Column('upsell_cooldown', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('progress_pct >= 0 AND progress_pct <= 100', name='chk_progress_pct'),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentors.mentor_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.parent_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('student_id'),
    sa.UniqueConstraint('parent_id')
    )
    op.create_index('idx_students_mentor_id', 'students', ['mentor_id'], unique=False)
    op.create_index('idx_students_parent_id', 'students', ['parent_id'], unique=False)
    op.create_index('idx_students_program', 'students', ['program'], unique=False)
    op.create_table('behavioral_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('session_start', sa.Time(), nullable=True),
    sa.Column('session_end', sa.Time(), nullable=True),
    sa.Column('studied', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('streak_day', sa.Integer(), server_default='0', nullable=False),
    sa.Column('score_delta', sa.Numeric(precision=4, scale=1), server_default='0', nullable=False),
    sa.Column('activities', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('mood_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'date', name='uq_behavioral_logs_student_date')
    )
    op.create_index('idx_behavioral_logs_student_date', 'behavioral_logs', ['student_id', 'date'], unique=False)
    op.create_index('idx_behavioral_logs_studied', 'behavioral_logs', ['student_id', 'date'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('ai_response', sa.Text(), nullable=False),
    sa.Column('context_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('escalated', sa.Boolean(), nullable=False),
    sa.Column('escalator_note', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.parent_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conversations_parent_timestamp', 'conversations', ['parent_id', 'timestamp'], unique=False)
    op.create_index('idx_conversations_student_id', 'conversations', ['student_id', 'timestamp'], unique=False)
    op.create_table('milestones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.String(length=50), nullable=False),
    sa.Column('milestone_id', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('score_label', sa.String(length=100), nullable=True),
    sa.Column('mentor_id', sa.Integer(), nullable=True),
    sa.Column('mentor_approved', sa.Boolean(), nullable=True),
    sa.Column('auth_score', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('contributor_type', sa.String(length=50), nullable=False),
    sa.Column('ai_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('auth_score IS NULL OR (auth_score >= 0 AND auth_score <= 100)', name='chk_auth_score'),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentors.mentor_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    ,
    sa.UniqueConstraint('student_id', 'milestone_id', name='uq_milestones_student_milestone_id')
    )
    op.create_index('idx_milestones_completed', 'milestones', ['student_id', 'date'], unique=False, postgresql_where="status = 'completed'")
    op.create_index('idx_milestones_essays', 'milestones', ['student_id', 'date'], unique=False)
    op.create_index('idx_milestones_student_date', 'milestones', ['student_id', 'date'], unique=False)
    op.create_index('idx_milestones_upcoming', 'milestones', ['student_id', 'date'], unique=False, postgresql_where="status = 'upcoming'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_milestones_upcoming', table_name='milestones', postgresql_where="status = 'upcoming'")
    op.drop_index('idx_milestones_student_date', table_name='milestones')
    op.drop_index('idx_milestones_essays', table_name='milestones')
    op.drop_index('idx_milestones_completed', table_name='milestones', postgresql_where="status = 'completed'")
    op.drop_table('milestones')
    op.drop_index('idx_conversations_student_id', table_name='conversations')
    op.drop_index('idx_conversations_parent_timestamp', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('idx_behavioral_logs_studied', table_name='behavioral_logs')
    op.drop_index('idx_behavioral_logs_student_date', table_name='behavioral_logs')
    op.drop_table('behavioral_logs')
    op.drop_index('idx_students_program', table_name='students')
    op.drop_index('idx_students_parent_id', table_name='students')
    op.drop_index('idx_students_mentor_id', table_name='students')
    op.drop_table('students')
    op.drop_index('idx_parents_student_id', table_name='parents')
    op.drop_index('idx_parents_email', table_name='parents')
    op.drop_table('parents')
    op.drop_index('mentors_programs_gin', table_name='mentors', postgresql_using='gin')
    op.drop_index('idx_mentors_email', table_name='mentors')
    op.drop_table('mentors')
    op.drop_index('idx_courses_program_season', table_name='courses')
    op.drop_index('courses_target_skills_gin', table_name='courses', postgresql_using='gin')
    op.drop_index('courses_suitable_for_gin', table_name='courses', postgresql_using='gin')
    op.drop_table('courses')
    # ### end Alembic commands ###
