"""init schema from current models

Revision ID: ee8d46d32bfd
Revises: 
Create Date: 2026-03-22 08:17:43.035098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee8d46d32bfd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etester_core',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.String(length=50), nullable=False),
    sa.Column('academic_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('writing_growth', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mentor_verifications', sa.Integer(), nullable=False),
    sa.Column('total_contributions', sa.Integer(), nullable=False),
    sa.Column('contributor_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pending_trace_links', sa.Integer(), nullable=False),
    sa.Column('pending_approvals', sa.Integer(), nullable=False),
    sa.Column('requirements_coverage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parent_support_level', sa.String(length=20), nullable=False),
    sa.Column('parent_engagement_count', sa.Integer(), nullable=False),
    sa.Column('institutional_stamp', sa.Boolean(), nullable=False),
    sa.Column('stamped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stamped_by', sa.Integer(), nullable=True),
    sa.Column('consistency_score', sa.Integer(), nullable=False),
    sa.Column('narrative_en', sa.Text(), nullable=True),
    sa.Column('narrative_vn', sa.Text(), nullable=True),
    sa.Column('narrative_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('badge_issued', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stamped_by'], ['mentors.mentor_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_index('idx_etester_core_student', 'etester_core', ['student_id'], unique=True)
    op.create_table('artifact_forms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('milestone_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=50), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('form_version', sa.String(length=10), nullable=False),
    sa.Column('form_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('blooms_level', sa.String(length=30), nullable=True),
    sa.Column('skills_practiced', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('had_leadership_role', sa.Boolean(), nullable=False),
    sa.Column('leadership_role_title', sa.String(length=255), nullable=True),
    sa.Column('leadership_team_size', sa.Integer(), nullable=True),
    sa.Column('leadership_outcome', sa.String(length=500), nullable=True),
    sa.Column('mentor_comment', sa.Text(), nullable=True),
    sa.Column('mentor_comment_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mentor_comment_by'], ['mentors.mentor_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('milestone_id')
    )
    op.create_index('idx_artifact_forms_student', 'artifact_forms', ['student_id'], unique=False)
    op.create_table('auth_scoring_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('milestone_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=50), nullable=False),
    sa.Column('auth_score', sa.Integer(), nullable=False),
    sa.Column('verdict', sa.String(length=30), nullable=False),
    sa.Column('dimension_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('explaining_artifacts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('explanation_en', sa.Text(), nullable=True),
    sa.Column('explanation_vn', sa.Text(), nullable=True),
    sa.Column('graph_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scored_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_auth_scoring_milestone', 'auth_scoring_results', ['milestone_id'], unique=False)
    op.create_index('idx_auth_scoring_student', 'auth_scoring_results', ['student_id'], unique=False)
    op.create_table('etester_badges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('core_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=50), nullable=False),
    sa.Column('badge_uid', sa.String(length=50), nullable=False),
    sa.Column('credential_type', sa.String(length=30), nullable=False),
    sa.Column('signed_token', sa.Text(), nullable=False),
    sa.Column('issuer_did', sa.String(length=100), nullable=False),
    sa.Column('badge_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoke_reason', sa.Text(), nullable=True),
    sa.Column('verify_count', sa.Integer(), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['core_id'], ['etester_core.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('badge_uid'),
    sa.UniqueConstraint('core_id')
    )
    op.create_index('idx_etester_badges_student', 'etester_badges', ['student_id'], unique=False)
    op.create_table('milestone_artifacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('milestone_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=50), nullable=False),
    sa.Column('full_text_content', sa.Text(), nullable=True),
    sa.Column('artifact_hash', sa.String(length=64), nullable=True),
    sa.Column('prev_artifact_hash', sa.String(length=64), nullable=True),
    sa.Column('vc_signature', sa.Text(), nullable=True),
    sa.Column('mentor_signed', sa.Boolean(), nullable=False),
    sa.Column('admin_signed', sa.Boolean(), nullable=False),
    sa.Column('manager_signed', sa.Boolean(), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('milestone_id')
    )
    op.create_index('idx_milestone_artifacts_student', 'milestone_artifacts', ['student_id'], unique=False)
    op.create_table('milestone_trace_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_milestone_id', sa.Integer(), nullable=False),
    sa.Column('to_milestone_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=50), nullable=False),
    sa.Column('relationship_type', sa.String(length=30), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('student_context_note', sa.Text(), nullable=True),
    sa.Column('student_noted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suggested_by_ai', sa.Boolean(), nullable=False),
    sa.Column('confirmed_by_mentor', sa.Boolean(), nullable=False),
    sa.Column('confirmed_by_mentor_id', sa.Integer(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("relationship_type IN ('experience_source', 'revision_of', 'mentor_guided', 'skill_applied', 'score_progression', 'recommends')", name='chk_relationship_type'),
    sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0', name='chk_trace_confidence'),
    sa.ForeignKeyConstraint(['confirmed_by_mentor_id'], ['mentors.mentor_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['from_milestone_id'], ['milestones.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_milestone_id'], ['milestones.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_milestone_id', 'to_milestone_id', name='uq_trace_link_pair')
    )
    op.create_index('idx_trace_links_pending', 'milestone_trace_links', ['student_id', 'confirmed_by_mentor'], unique=False)
    op.create_index('idx_trace_links_student', 'milestone_trace_links', ['student_id'], unique=False)
    op.create_table('mentor_verifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('milestone_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=50), nullable=False),
    sa.Column('verifier_id', sa.Integer(), nullable=False),
    sa.Column('verifier_type', sa.String(length=20), nullable=False),
    sa.Column('action_type', sa.String(length=30), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('trace_link_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trace_link_id'], ['milestone_trace_links.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mentor_verif_milestone', 'mentor_verifications', ['milestone_id'], unique=False)
    op.create_index('idx_mentor_verif_student', 'mentor_verifications', ['student_id'], unique=False)
    op.add_column('managers', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('idx_managers_email'), table_name='managers')
    op.drop_constraint(op.f('managers_email_key'), 'managers', type_='unique')
    op.create_unique_constraint(None, 'managers', ['user_id'])
    op.create_foreign_key(None, 'managers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('managers', 'email')
    op.drop_column('managers', 'hashed_password')
    op.add_column('mentors', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('idx_mentors_email'), table_name='mentors')
    op.drop_constraint(op.f('mentors_email_key'), 'mentors', type_='unique')
    op.create_unique_constraint(None, 'mentors', ['user_id'])
    op.create_foreign_key(None, 'mentors', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('mentors', 'email')
    op.drop_column('mentors', 'hashed_password')
    op.create_unique_constraint('uq_milestones_student_milestone_id', 'milestones', ['student_id', 'milestone_id'])
    op.add_column('parents', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('idx_parents_email'), table_name='parents')
    op.drop_constraint(op.f('parents_email_key'), 'parents', type_='unique')
    op.create_unique_constraint(None, 'parents', ['user_id'])
    op.create_foreign_key(None, 'parents', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('parents', 'email')
    op.drop_column('parents', 'hashed_password')
    op.add_column('students', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index('idx_students_user_id', 'students', ['user_id'], unique=False)
    op.create_unique_constraint(None, 'students', ['user_id'])
    op.create_foreign_key(None, 'students', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_constraint(None, 'students', type_='unique')
    op.drop_index('idx_students_user_id', table_name='students')
    op.drop_column('students', 'user_id')
    op.add_column('parents', sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('parents', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'parents', type_='foreignkey')
    op.drop_constraint(None, 'parents', type_='unique')
    op.create_unique_constraint(op.f('parents_email_key'), 'parents', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_parents_email'), 'parents', ['email'], unique=False)
    op.drop_column('parents', 'user_id')
    op.drop_constraint('uq_milestones_student_milestone_id', 'milestones', type_='unique')
    op.add_column('mentors', sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('mentors', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'mentors', type_='foreignkey')
    op.drop_constraint(None, 'mentors', type_='unique')
    op.create_unique_constraint(op.f('mentors_email_key'), 'mentors', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_mentors_email'), 'mentors', ['email'], unique=False)
    op.drop_column('mentors', 'user_id')
    op.add_column('managers', sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('managers', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'managers', type_='foreignkey')
    op.drop_constraint(None, 'managers', type_='unique')
    op.create_unique_constraint(op.f('managers_email_key'), 'managers', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_managers_email'), 'managers', ['email'], unique=False)
    op.drop_column('managers', 'user_id')
    op.drop_index('idx_mentor_verif_student', table_name='mentor_verifications')
    op.drop_index('idx_mentor_verif_milestone', table_name='mentor_verifications')
    op.drop_table('mentor_verifications')
    op.drop_index('idx_trace_links_student', table_name='milestone_trace_links')
    op.drop_index('idx_trace_links_pending', table_name='milestone_trace_links')
    op.drop_table('milestone_trace_links')
    op.drop_index('idx_milestone_artifacts_student', table_name='milestone_artifacts')
    op.drop_table('milestone_artifacts')
    op.drop_index('idx_etester_badges_student', table_name='etester_badges')
    op.drop_table('etester_badges')
    op.drop_index('idx_auth_scoring_student', table_name='auth_scoring_results')
    op.drop_index('idx_auth_scoring_milestone', table_name='auth_scoring_results')
    op.drop_table('auth_scoring_results')
    op.drop_index('idx_artifact_forms_student', table_name='artifact_forms')
    op.drop_table('artifact_forms')
    op.drop_index('idx_etester_core_student', table_name='etester_core')
    op.drop_table('etester_core')
    # ### end Alembic commands ###
