import { Sparkles, RefreshCw } from 'lucide-react'

interface NarrativeCardProps {
  narrative: string
  studentName?: string
  onRefresh?: () => void
}

export default function NarrativeCard({ narrative, studentName, onRefresh }: NarrativeCardProps) {
  return (
    <div className="bg-etest-blue-light rounded-3xl p-8 relative overflow-hidden">
      <div className="absolute top-0 right-0 w-40 h-40 bg-etest-blue/5 rounded-full -mr-16 -mt-16 blur-3xl pointer-events-none" />
      <div className="relative z-10">
        <div className="flex items-center justify-between mb-4">
          <h3 className="font-bold text-etest-text">
            {studentName ? `Learning journey of ${studentName}` : 'Câu chuyện của bạn'}
          </h3>
          <span className="inline-flex items-center gap-1.5 px-3 py-1 bg-etest-blue/10 text-etest-blue text-[10px] font-bold rounded-full uppercase tracking-wider">
            <Sparkles className="w-3 h-3" />
            Generated by AI
          </span>
        </div>
        <p className="text-sm text-etest-subtext leading-relaxed whitespace-pre-line">
          {narrative}
        </p>
        {onRefresh && (
          <button
            onClick={onRefresh}
            className="mt-4 inline-flex items-center gap-2 text-sm font-semibold text-etest-blue hover:text-etest-blue-dark transition-colors"
          >
            Refresh narrative
            <RefreshCw className="w-3.5 h-3.5" />
          </button>
        )}
      </div>
    </div>
  )
}
